args:
    device: 'cuda'
    train_style: 'interpolate' 
    results_dir: './1D_results_fno_nodropout_fix_4s/'
    num_workers: 0
    batch_size: 128
    initial_step: 4
    interval: 16
    rollout_length: 1
    t_train: 200
    validate: 1
    flnm: 'Heat'
    #flnm: 'Burgers'
    #flnm: 'KdV'
    data_name: 'varied_heat_10000.h5'
    #data_name: 'varied_burgers_2500.h5'
    #data_name: 'varied_kdv_2500.h5'
    base_path: './pde_data/'
    return_text: False
    reduced_resolution: 1
    reduced_resolution_t: 1
    reduced_batch: 1


    # Optimizer
    learning_rate: 1.e-3
    weight_decay: 1.e-5
    scheduler_step: 200
    scheduler_gamma: 0.1
    training_type: single
    epochs: 100
    num_seeds: 5

    # Sim samples
    num_t: 100
    num_x: 100
    sim_time: 1
    num_samples:

    # FNO
    num_channels: 1
    modes: 4
    width: 64
    #width: 100
    dropout: 0.0 # Default

    # Tracking
    log_freq: 1
    progress_plot_freq: 10
